# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2

updates:
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
